sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.8.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo mv docker-compose /usr/local/bin
  - chmod +x /usr/local/bin/docker-compose

  - docker version

  - docker build --no-cache -t m9rco/alpine:3.5 -f 3.5/Dockerfile 3.5/
  - docker build --no-cache -t m9rco/alpine:3.5-dev -f 3.5/Dockerfile.dev 3.5/

  - docker build --no-cache -t m9rco/alpine:3.8 -f 3.8/Dockerfile 3.8/
  - docker build --no-cache -t m9rco/alpine:3.8-dev -f 3.8/Dockerfile.dev 3.8/

  - docker run --name alpine3.5 -d -v $PWD:/app m9rco/alpine:3.5
  - docker run --name alpine3.5-dev -d -v $PWD:/app m9rco/alpine:3.5-dev

  - docker run --name alpine3.8 -d -v $PWD:/app m9rco/alpine:3.8
  - docker run --name alpine3.8-dev -d -v $PWD:/app m9rco/alpine:3.8-dev

script:
  - docker exec alpine3.5-dev sh -c "apk -V"
  - docker exec alpine3.8-dev sh -c "apk -V"
